version: "3.9"

networks:
  development:
  test:

volumes:
  db_data:
  gem_cache:
  yarn_cache:
  shared_data:
  node_modules:

services:
  db:
    image: postgres:13.4-alpine
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data
      - shared_data:${SHARED_DATA_PATH:-/var/shared}
    networks:
      - development
      - test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  app:
    image: rails_app
    build:
      context: .
      dockerfile: Dockerfile.development
      args:
        APP_PATH: ${APP_PATH:-/var/app}
        BUNDLE_VERSION: 2.2.27
        BUNDLE_PATH: ${BUNDLE_PATH:-/usr/local/bundle/gems}
        TMP_PATH: /tmp/
        RAILS_LOG_TO_STDOUT: "true"
        RAILS_PORT: 3000
    container_name: app
    volumes:
      - .:${APP_PATH:-/var/app}
      - shared_data:${SHARED_DATA_PATH:-/var/shared}
      - gem_cache:${BUNDLE_PATH:-/usr/local/bundle/gems}
      - yarn_cache:${YARN_CACHE_PATH:-/usr/local/share/.cache/yarn/v6}
      - node_modules:${APP_PATH:-/var/app}/node_modules
    networks:
      - development
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    env_file: .env.development
    entrypoint: ./entrypoint-dev.sh
    command: ["rails", "server", "-p", "3000", "-b", "0.0.0.0"]
    environment:
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: webpacker
    depends_on:
      - db
      - webpacker
  webpacker:
    image: rails_app
    container_name: webpacker
    entrypoint: ./entrypoint-webpacker.sh
    command: ["./bin/webpack-dev-server"]
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    volumes:
      - .:${APP_PATH:-/var/app}
      - shared_data:${SHARED_DATA_PATH:-/var/shared}
      - gem_cache:${BUNDLE_PATH:-/usr/local/bundle/gems}
      - yarn_cache:${YARN_CACHE_PATH:-/usr/local/share/.cache/yarn/v6}
      - node_modules:${APP_PATH:-/var/app}/node_modules
    networks:
      - development
      - test
    ports:
      - '3035:3035'
  test:
    image: rails_app
    container_name: test
    volumes:
      - .:${APP_PATH:-/var/app}
      - shared_data:${SHARED_DATA_PATH:-/var/shared}
      - gem_cache:${BUNDLE_PATH:-/usr/local/bundle/gems}
      - yarn_cache:${YARN_CACHE_PATH:-/usr/local/share/.cache/yarn/v6}
      - node_modules:${APP_PATH:-/var/app}/node_modules
    networks:
      - test
    ports:
      - 3002:3000
    stdin_open: true
    tty: true
    env_file: .env.test
    entrypoint: ./entrypoint-test.sh
    command: ["autotest"]
    environment:
      RAILS_ENV: test
    depends_on:
      - db
  systemtest:
    image: rails_app
    container_name: systemtest
    volumes:
      - .:${APP_PATH:-/var/app}
      - shared_data:${SHARED_DATA_PATH:-/var/shared}
      - gem_cache:${BUNDLE_PATH:-/usr/local/bundle/gems}
      - yarn_cache:${YARN_CACHE_PATH:-/usr/local/share/.cache/yarn/v6}
      - node_modules:${APP_PATH:-/var/app}/node_modules
    networks:
      - test
    ports:
      - 3001:3001
    stdin_open: true
    tty: true
    env_file: .env.test
    entrypoint: ./entrypoint-systemtest.sh
    command: ["rails", "test:system"]
    environment:
      RAILS_ENV: test
      NODE_ENV: test
    depends_on:
      - db
      - selenium
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome-debug
    networks:
      - test
    ports:
      - "4444:4444"
      - "5900:5900"
    volumes:
      - /dev/shm:/dev/shm
    stdin_open: true
    tty: true
    environment:
      VNC_PASSWORD: 'secret'
      GRID_DEBUG: "true"
      DEBUG: "true"
